# .air.toml

# Configurations for air live reload
root = "."
tmp_dir = "tmp"
build = "go build -o ./tmp/main main.go"
cmd = "./tmp/main"

# Watch and ignore specific files
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]
