# Use a specific Go version for consistency
FROM golang:1.23-alpine

# Install dependencies
RUN apk add --no-cache git curl

# Set the working directory inside the container
WORKDIR /app

# Install air for live reloading using the new path
RUN go install github.com/air-verse/air@latest

# Copy go.mod and go.sum files to cache dependencies
COPY go.mod go.sum ./

# Download Go modules
RUN go mod download

# Copy the rest of the application source code
COPY . .

# Expose the port the API Gateway will run on
EXPOSE 8080

# Start the app with air for live reloading
CMD ["air"]
